version: 1.0.{build}
image: WMF 5
init:
- ps: $deploy = "`$vmwfs14 = New-PSSession -ComputerName VMWFS14`nRemove-Item -Path `"`${Env:APPLICATION_PATH}\`${Env:APPVEYOR_PROJECT_SLUG}\appveyor.yml`"`nRemove-Item -Path `"`${Env:APPLICATION_PATH}\`${Env:APPVEYOR_PROJECT_SLUG}\.gitignore`" -Force`nRemove-Item -Path `"`${Env:APPLICATION_PATH}\`${Env:APPVEYOR_PROJECT_SLUG}\.gitattributes`" -Force`nRemove-Item -Path `"`${Env:APPLICATION_PATH}\`${Env:APPVEYOR_PROJECT_SLUG}\Tests`" -Recurse`nRemove-Item -Path `"`${Env:APPLICATION_PATH}\`${Env:APPVEYOR_PROJECT_SLUG}\.git`" -Recurse -Force`nCopy-Item -Path `"`${Env:APPLICATION_PATH}\`${Env:APPVEYOR_PROJECT_SLUG}`" -Destination `"H:\Archive\SCCM\Staging\`${Env:APPVEYOR_PROJECT_NAME}\`${Env:APPVEYOR_BUILD_VERSION}`" -ToSession `$vmwfs14 -Recurse"`nImport-Module -Name `"`$(Split-Path `$Env:SMS_ADMIN_UI_PATH)\ConfigurationManager.psd1`"`nSet-Location -Path MS1:`nNew-CMApplication -Name `"AppVeyor - `${APPVEYOR_PROJECT_NAME}`" -AutoInstall `$true
install:
- ps: >-
    Install-PackageProvider -Name NuGet –Force

    Install-Package -Name Pester -ProviderName PowerShellGet -Scope AllUsers -Force

    Install-Module -Name PSScriptAnalyzer -Scope AllUsers –Force

    Import-Module -Name Pester

    Import-Module -Name PSScriptAnalyzer

    7z a -tzip "${Env:APPVEYOR_BUILD_FOLDER}\${Env:APPVEYOR_PROJECT_NAME}.zip" "${Env:APPVEYOR_BUILD_FOLDER}"

    $deploy | Out-File "${Env:APPVEYOR_BUILD_FOLDER}\deploy.ps1"

    7z a -tzip "${Env:APPVEYOR_BUILD_FOLDER}\deploy.zip" "deploy.ps1"
build: off
test_script:
- ps: >-
    $testResultsFile = ".\TestsResults.xml"

    $results = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru

    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))

    If ($results.FailedCount -gt 0) {
      throw "$($results.FailedCount) tests failed."
    }
artifacts:
- path: '*.zip'
  name: VMWFS14
deploy:
- provider: Environment
  name: VMWFS14
  on:
    branch: master
