version: 1.0.{build}
image: WMF 5
init:
- ps: >-
    $deploy = @"

    `$vmwfs14 = New-PSSession -ComputerName VMWFS14

    Remove-Item -Path "`${Env:APPLICATION_PATH}\`${Env:APPVEYOR_PROJECT_SLUG}\appveyor.yml"

    Remove-Item -Path "`${Env:APPLICATION_PATH}\`${Env:APPVEYOR_PROJECT_SLUG}\.gitignore" -Force

    Remove-Item -Path "`${Env:APPLICATION_PATH}\`${Env:APPVEYOR_PROJECT_SLUG}\.gitattributes" -Force

    Remove-Item -Path "`${Env:APPLICATION_PATH}\`${Env:APPVEYOR_PROJECT_SLUG}\.git" -Recurse -Force

    Remove-Item -Path "`${Env:APPLICATION_PATH}\`${Env:APPVEYOR_PROJECT_SLUG}\Tests" -Recurse

    Copy-Item -Path "`${Env:APPLICATION_PATH}\`${Env:APPVEYOR_PROJECT_SLUG}" -Destination "H:\Archive\SCCM\Staging\`${Env:APPVEYOR_PROJECT_NAME}\`${Env:APPVEYOR_BUILD_VERSION}" -ToSession `$vmwfs14 -Recurse

    Import-Module -Name "`$(Split-Path `$Env:SMS_ADMIN_UI_PATH)\ConfigurationManager.psd1"

    New-PSDrive -Name "MS1" -PSProvider "AdminUI.PS.Provider\CMSite" -Root "VMWAS117" -Description "MS1"

    Set-Location -Path MS1:

    New-CMApplication -Name "Staging - `${Env:APPVEYOR_PROJECT_NAME}" -AutoInstall `$true

    Add-CMDeploymentType -ApplicationName "Staging - `${Env:APPVEYOR_PROJECT_NAME}" -DeploymentTypeName "Staging - `${Env:APPVEYOR_PROJECT_NAME} `${Env:APPVEYOR_BUILD_VERSION} PowerShell App Deployment Toolkit" -InstallationProgram "Deploy-Application.exe" -AdministratorComment "AppVeyor test" -AllowClientsToShareContentOnSameSubnet `$true -ContentLocation "\\vmwfs14\H`$\Archive\SCCM\Staging\`${Env:APPVEYOR_PROJECT_NAME}\`${Env:APPVEYOR_BUILD_VERSION}" -InstallationBehaviorType "InstallForSystem" -InstallationProgramVisibility "Normal" -LogonRequirementType "WhetherOrNotUserLoggedOn" -MaximumAllowedRunTimeMinutes 720 -PersistContentInClientCache `$false -RunInstallationProgramAs32BitProcessOn64BitClient `$false -UninstallProgram "Deploy-Application.exe -DeploymentType `"Uninstall`""

    "@
install:
- ps: >-
    Install-PackageProvider -Name NuGet –Force

    Install-Package -Name Pester -ProviderName PowerShellGet -Scope AllUsers -Force

    Install-Module -Name PSScriptAnalyzer -Scope AllUsers –Force

    Import-Module -Name Pester

    Import-Module -Name PSScriptAnalyzer

    7z a -tzip "${Env:APPVEYOR_BUILD_FOLDER}\${Env:APPVEYOR_PROJECT_NAME}.zip" "${Env:APPVEYOR_BUILD_FOLDER}"

    $deploy | Out-File "${Env:APPVEYOR_BUILD_FOLDER}\deploy.ps1"

    7z a -tzip "${Env:APPVEYOR_BUILD_FOLDER}\deploy.zip" "deploy.ps1"
build: off
test_script:
- ps: >-
    $testResultsFile = ".\TestsResults.xml"

    $results = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru

    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($Env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))

    If ($results.FailedCount -gt 0) {
      throw "$($results.FailedCount) tests failed."
    }
artifacts:
- path: '*.zip'
  name: VMWFS14
deploy:
- provider: Environment
  name: VMWFS14
  on:
    branch: master
